name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry and pre-commit
        run: |
          pipx install poetry
          pipx install pre-commit
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
